[project]
name = "gen-ai-cohort"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.100.1",
    "python-dotenv>=1.1.1",
    "tiktoken>=0.11.0",
]
